ALTER TABLE APP.DISH ADD COLUMN DELETED BOOLEAN DEFAULT FALSE;
UPDATE APP.DISH SET DELETED = FALSE WHERE DELETED IS NULL;
CREATE VIEW APP.DISHVIEW AS SELECT ID, NAME, TYPE FROM APP.DISH WHERE DELETED = FALSE;
CREATE VIEW APP.DELETEDDISHVIEW AS SELECT ID, NAME, TYPE FROM APP.DISH WHERE DELETED = TRUE;
